# -*- coding: utf-8 -*-
"""Normal_Equation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HxKqKmSfQWSImwR20vzrLPlJa9I21hKE
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D

def NormalEqn(X,y):
  theta = np.zeros((len(X),1))
  theta = np.dot(np.dot(np.linalg.inv(np.dot(X.transpose(),X)) , X.transpose()), y)
  
  return theta

data = pd.read_csv('ex1data2.txt',header=None)

data_n = data.values
m2 = len(data_n[:,-1])
X2 = data_n[:,0:2].reshape(m2,2)
X2 = np.append(np.ones((m2,1)),X2,axis=1)
y2=data_n[:,-1].reshape(m2,1)

theta = NormalEqn(X2,y2)

theta

def predict(X,theta):
  predictions = np.dot(theta.transpose(),X)
  
  return predictions[0]

x_sample = np.array([1650,3])
x_sample=np.append(np.ones(1),x_sample)
predict3=predict(x_sample,theta)
print("For size of house = 1650, Number of bedroom = 3, we predict a house value of $"+str(round(predict3,0)))

